language: python
python:
  - "3.7"
install:
  - pip install coveralls
  - python setup.py install
script:
  - python -m unittest
  - coverage run --source sshmanager setup.py test

after_success:
    coveralls
